# Site settings
title: 어? 쓰흡... 하아....
SEOTitle: 어? 쓰흡... 하아.... | Dev X
header-img: img/home-bg.jpg
email: developer.kje@gmail.com
description: "프론트 엔드 개발 희망 | HTML, CSS, SCSS, vanila js 그리고 react 조금"
keyword: "DevX, "
url: "https://dkje.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# zhihu_username: huxpro
github_username: dkje
# twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
    input: GFM # use Github Flavored Markdown !important
    syntax_highlighter_opts:
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1

# Disqus settings
disqus_username: dkje

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-175496877-1" # Format: UA-xxxxxx-xx
ga_domain: dkje.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "프론트 엔드 | 공부 중!"
sidebar-avatar: /img/avatar.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
    [
        { title: "woojun Kang", href: "https://velog.io/@woojun_kang" },
        { title: "Gray", href: "https://dev-gp.tistory.com/" },
        { title: "Paul Kim", href: "https://velog.io/@paulkim" },
    ]
